# -*- coding: utf-8 -*-

{
    'name': 'pms',
    'version': '18.0.1.2.0',
    'category': 'Services/pms',
    'license': 'LGPL-3',
    'depends': ['base', 'base_automation', 'account_payment', 'account', 'account_accountant', 'documents', 'analytic', 'purchase', 'stock', 'sale', 'hr_expense', 'l10n_us_1099', 'account_batch_payment', 'maintenance'],
    'description': "Module to manage real estate properties",
    'installable': True,
    'application': True,
    'data': [
        'security/group.xml',
        'security/ir.model.access.csv',
        'views/internal_purchases.xml',
        'views/email_template_inherit.xml',
        'views/pms_properties_utility_view.xml',
        'views/pms_utility_electrical.xml',
        'views/pms_utility_water.xml',
        'views/pms_utility_sewage.xml',
        'views/pms_properties_transaction_view.xml',
        'views/pms_properties_insurance_view.xml',
        'views/pms_properties_insuranceline.xml',
        'views/pms_housedetails.xml',
        'views/contact_liabilityinsurance.xml',
        'views/purchase_views.xml',
        'views/pms_inspections.xml',
        'views/pms_inspections_type.xml',
        'views/pms_loans.xml',
        'views/pms_materials.xml',
        'views/stock_material_history.xml',
        'views/pms_draws.xml',
        'views/pms_approvals_view.xml',
        'views/pms_projects_routes.xml',
        'views/purchase_template.xml',
        'views/pms_projects.xml',
        'views/pms_properties_view.xml',
        'views/pms_provider_config_view.xml',
        'views/pms_draw_items.xml',
        'views/pms_draw_lines.xml',
        'views/pms_job_creation.xml',
        'views/pms_on_hold_history.xml',
        'views/pms_project_summary.xml',
        # 'views/pms_leads.xml',
        'views/pms_visit_days.xml',
        'views/pms_inversionistas.xml',
        'views/pms_investors_reports.xml',
        'wizard/commission_calculation_wizard.xml',
        'views/pms_menu.xml',
        'reports/pms_purchases_report_view.xml',
        'reports/pms_templates.xml',
        'reports/pms_reports.xml',
        'reports/budgeting_report.xml',
        'reports/property_times_report.xml',
        'reports/expected_co_report.xml',
        'reports/customer_messages_dashboard.xml',
        'reports/approve_bill.xml',
        'reports/duplicate_products.xml',
        'reports/duplicate_reference.xml',
        'reports/daily_log_report.xml',
        'reports/contractor_job_report.xml',
        'reports/draws_report.xml',
        'reports/tax_1099_report.xml',
        'reports/vendor_1099_compliance.xml',
        'reports/unified_work_orders.xml',
        'reports/construction_fee_audit.xml',
        'views/res_config_settings.xml',
        'views/account_invoice_change_pms.xml',
        'views/account_move.xml',
        'views/sale_order_view.xml',
        'views/check_maker.xml',
        'views/hr_employee.xml',
        'views/check_url.xml',
        'views/account_messages.xml',
        'views/account_bank.xml',
        # 'views/product_subproduct.xml',
        # 'views/product_template.xml',
        'views/pms_leads.xml',
        'views/pms_checklist.xml',
        'views/pms_contractors.xml',
        'views/pms_incidences.xml',
        'views/pms_materials_followup.xml',
        'views/pms_portfolio.xml',
        'views/pms_activity_costs.xml',
        'views/pms_inspections_failures.xml',
        'wizard/account_bill_wizard_views.xml',
        'wizard/mat_order_bill_wizard.xml',
        'wizard/pms_new_bulk_wizard.xml',
        'wizard/pms_close_property.xml',
        'wizard/budget_check_wizard.xml',
        'wizard/message_crm_wizard.xml',
        'wizard/pms_transactions_journal_wizard.xml',
        'wizard/auto_planned_visits.xml',
        'wizard/create_material_orders_wizard.xml',
        'wizard/daily_logs.xml',
        'wizard/intercompany_payment.xml',
        'wizard/no_availability_wizard.xml',
        'wizard/approve_bill_wizard.xml',
        'reports/pms_visit_report.xml',
        'reports/analytic_bs_report.xml',
        'reports/analytic_pl_report.xml',
        'reports/analytic_pl_cash_report.xml',
        'reports/analytic_bs_cash_report.xml',
        'reports/analytic_items_report.xml',
        'reports/material_provider_report.xml',
        'reports/construction_general_report.xml',
        'reports/supervisor_inspections_report.xml',
        'reports/construction_utilities_report.xml',
        'reports/purchases_general_report.xml',
        'reports/invoice_report.xml',
        # 'reports/journal_items_cash_report.xml',
        'reports/bill_report.xml',
        'reports/bill_invoice_grouped_report.xml',
        'reports/property_timeline_report.xml',
        'reports/property_loan_report.xml',
        'reports/tetcho_invoice_template.xml',
        'reports/tetcho_invoice_template_2.xml',
        'reports/freshcut_invoice_template.xml',
        'reports/rent_report.xml',
        'reports/pms_phases_report.xml',
        'views/pms_units_view.xml',
        'views/pms_property_report.xml',
        'views/account_payment.xml',
        'views/account_account.xml',
        'views/account_recurring.xml',
        'views/documents.xml',
        'wizard/create_check_wizard.xml',
        'wizard/ask_approve_wizard.xml',
        'wizard/dispute_wizard.xml',
        'wizard/failed_inspect_wizard.xml',
        'views/product_subproduct.xml',
        'views/pms_phase_times.xml',
        'views/product_template.xml',
        'views/crm_lead.xml',
        'wizard/verification_wizard_views.xml',
        'wizard/product_price_wizard.xml',
        'wizard/pms_orderjobs_wizard.xml',
        'wizard/visit_day_project.xml',
        'wizard/budget_date_wizard.xml',
        'wizard/invoice_wizard.xml',
        'wizard/pms_request_draw_wizard.xml',
        'wizard/account_customer_messages_wizard.xml',
        'views/account_report_templates.xml',
        'data/county.xml',
        'data/cities.xml',
        'data/scheduled_actions.xml',
    ],
}
